# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  LElbow_Pitch: #-170~170
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.96706
    min_position: -2.96706
  LElbow_Yaw:   #-90~47
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.820
    min_position: -1.57
  LFinger_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger_1_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger_2_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LFinger_3_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulder_Pitch:  #-170~170
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.96
    min_position: -2.96
  LShoulder_Roll: #-100~94
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.64061
    min_position: -1.74533
  LWrist_Pitch:   #-164~170
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.96706
    min_position: -2.86234
  LWrist_Roll:  #
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RElbow_Pitch: #-164~170
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.96706
    min_position: -2.86234
  RElbow_Yaw:  #-47~90
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.5708
    min_position: -0.820305
  RFinger_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger_1_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger_2_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RFinger_3_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulder_Pitch:  #-171~171
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.98451
    min_position: -2.98451
  RShoulder_Roll: #-94~100
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.74533
    min_position: -1.64061
  RWrist_Pitch:   #-164~170
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.96706
    min_position: -2.86234
  RWrist_Roll:  #-55~52
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.907571
    min_position: -0.959931
  Waist_Pitch:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.488
    min_position: -0.488
  Waist_Roll:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.30
    min_position: -0.30
