#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Social Robot Arm usb connection."
echo ""

sudo cp `rospack find social_robot_arm_controller`/99-social-robot-arm-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
